version: "3.8"
services:
    mongo:
        image: mongo:6.0
        container_name: teencare-mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db
    app:
        build: .
        container_name: teencare-app
        restart: always
        ports:
            - 4000:4000
        env_file:
            - .env
        depends_on:
            - mongo
volumes:
    mongo_data:
